export default {
  products: [
    {
      _id: ' ',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '../public/p1.jpg',
      price: 60,
      brand: ' Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
    },
    {
      _id: '2',
      name: "Super Mario Odyssey",
      description: 'Super Mario Odyssey is a platform game in which players control Mario as he travels across many different worlds, known as "Kingdoms" within the game, on the hat-shaped ship Odyssey, to rescue Princess Peach from Bowser, who plans to forcibly marry her.',
      numReviews: 10,
      category: 'Plataform',
      brand: 'Nintedo',
      rating: 4.5,
      price: 197.88,
      score: 100,
      image: require("./images/super-mario-odyssey.png"),
      quantity: 12
    },
    {
      _id: '3',
      name: "Call Of Duty Infinite Warfare",
      description: "It is the first title by Infinity Ward under the new three-year development cycle for the Call of Duty series. The game's campaign is centered around a battle for the Solar System, which the Settlement Defense Front (SDF), a hostile force who are the main antagonists, are attempting to take over.",
      numReviews: 10,
      category: 'First-person shooter',
      brand: 'Activision',
      rating: 4.5,
      price: 49.99,
      score: 80,
      image: require("./images/call-of-duty-infinite-warfare.png"),
      quantity: 3
    },
    {
      _id: '4',
      name: "The Witcher III Wild Hunt",
      description: 'The Witcher 3: Wild Hunt is an action role-playing game with a third-person perspective. Players control Geralt of Rivia, a monster slayer known as a Witcher. Geralt walks, runs, rolls and dodges, and (for the first time in the series) jumps, climbs and swims',
      numReviews: 10,
      category: 'Action role-playing',
      brand: 'CD Projekt Red',
      rating: 4.5,
      price: 119.5,
      score: 250,
      image: require("./images/the-witcher-iii-wild-hunt.png"),
      quantity: 1
    },
    {
      _id: '10',
      name: "Call Of Duty WWII",
      description: "Call of Duty: WWII is the fourteenth game in the Call of Duty franchise and Sledgehammer Games' second to be developed in a three-year development cycle. Set during World War II, it tells the story of an unbreakable brotherhood of common men fighting to preserve freedom in a world on the brink of tyranny.",
      numReviews: 10,
      category: 'First-person shooter',
      brand: 'Activision',
      rating: 1.5,
      price: 249.99,
      score: 205,
      image: require("./images/call-of-duty-wwii.png"),
      quantity: 0
    },
    {
      _id: '5',
      name: "Mortal Kombat XL",
      description: 'Mortal Kombat X is a fighting game in which two characters fight against each other using a variety of attacks, including special moves, and the series trademark gruesome finishing moves. The game allows two players to face each other (either locally or online), or a single player to play against the CPU',
      numReviews: 10,
      category: 'fight',
      studio: 'NetherRealm Studios',
      rating: 4.5,
      price: 69.99,
      score: 150,
      image: require("./images/mortal-kombat-xl.png"),
      quantity: 2
    },
    {
      _id: '6',
      name: "Shards of Darkness",
      description: "Explore and master huge open environments, sneak past or assassinate new enemies and bosses, and experiment with the new array of lethal abilities and weapons in our goblin assassin's arsenal. Sneak your way alone, or with a friend in coop mode!",
      numReviews: 10,
      category: 'Stealth',
      studio: 'Focus Home Interactive, Cyanide',
      rating: 4.5,
      price: 71.94,
      score: 400,
      image: require("./images/shards-of-darkness.png"),
      quantity: 7
    },
    {
      _id: '7',
      name: "Terra Média: Sombras de Mordor",
      description: 'Middle-earth: Shadow of Mordor is a third-person open world action-adventure video game, where the player controls a ranger by the name of Talion who seeks revenge on the forces of Sauron after his family, consisting of his wife and son, are killed by those that lead them.',
      numReviews: 10,
      category: 'RPG',
      studio: 'Warner Bros. Interactive Entertainment',
      rating: 4.5,
      price: 79.99,
      score: 50,
      image: require("./images/terra-media-sombras-de-mordor.png"),
      quantity: 0
    },
    {
      _id: '8',
      name: "FIFA 18",
      description: 'FIFA 18 is a football simulation video game developed and published by Electronic Arts and released worldwide on 29 September 2017',
      numReviews: 10,
      category: 'Soccer',
      studio: 'Eletronic Arts EA',
      rating: 4.5,
      price: 195.39,
      score: 325,
      image: require("./images/fifa-18.png"),
      quantity: 1
    },
    {
      _id: '9',
      name: "Horizon Zero Dawn",
      description: 'Horizon Zero Dawn is a 2017 action role-playing game developed by Guerrilla Games and published by Sony Interactive Entertainment. The plot follows Aloy, a young huntress in a world overrun by machines, who sets out to uncover her past.',
      numReviews: 10,
      category: 'action role-playing',
      studio: 'Guerrilla Games Sony Interactive Entertainment',
      rating: 4.5,
      price: 115.8,
      score: 290,
      image: require("./images/horizon-zero-dawn.png"),
      quantity: 0
    }
  ]
}